app:
  debug: true
modules:
  sql:
    driver: sqlite
    dsn: ":memory:"
    migrations:
      stdout: false
  log:
    output: test
  trace:
    processor:
      type: test
config:
  dashboard:
    title: Test dashboard title
  seed:
    orders:
      alice: frontend
      bob: backend
      carl: backend
      dan: frontend
      elvis: backend
